### ISSUE TITLE
On restart adapter deletes all activities (and objects / channels) and recreates them

### ISSUE THREAD

**Issue by Garfonso** [Pmant/ioBroker.harmony#39]
I recently noticed that the adapter, on a restart or even a reconnect deletes all objects for all activities and most channels (or all?) and recreates them with the exact same name. Attached is a log for this.
[harmony.log](https://github.com/Pmant/ioBroker.harmony/files/2700310/harmony.log)

Not sure why the "new activities" have a _ instead of spaces. In the harmony app they show up with spaces and were created using spaces. Also the new objects and channels created contain spaces. Maybe this got broken for trying to fix the forbidden characters problematic? 

This is with version 1.0.0 of the adapter and js-controller 1.4.2 and node version 10.14.2, npm version 6.4.1 on a Ubuntu system.

**Comment by Pmant** [comment]
I changed the adapter to allow spaces in all states/objects (e.g. hub name) since the ioBroker team specified spaces as a valid char for states ids. 
Some people complained since the renaming broke their scripts so it got reverted with one of the latest commits, maybe incomplete.
I can't debug this right now since Logitech decided to close this XMPP-Port #38.

**Comment by foxriver76** [comment]
You have not deleted the devices once after upgrading to 1.0.0. Based on the log there are blank spaces in your names, if you delete all channels once, they will be recreated with underscores.

With blank names, it cannot be detected, that the devices are already created, because of an issue in js-controller 1.4.2.
